# 
# Synthesis run script generated by Vivado
# 

debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7vx485tffg1761-2

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {C:/Users/Arkadiusz/Documents/Vivado Projects/TDC_VernierOsc/TDC_VernierOsc.cache/wt} [current_project]
set_property parent.project_path {C:/Users/Arkadiusz/Documents/Vivado Projects/TDC_VernierOsc/TDC_VernierOsc.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part xilinx.com:vc707:part0:1.2 [current_project]
read_vhdl -library xil_defaultlib {
  {C:/Users/Arkadiusz/Documents/Vivado Projects/TDC_VernierOsc/TDC_VernierOsc.srcs/sources_1/new/NAND_chain.vhd}
  {C:/Users/Arkadiusz/Documents/Vivado Projects/TDC_VernierOsc/TDC_VernierOsc.srcs/sources_1/new/INV_chain_13.vhd}
  {C:/Users/Arkadiusz/Documents/Vivado Projects/TDC_VernierOsc/TDC_VernierOsc.srcs/sources_1/imports/new/DFF with set.vhd}
  {C:/Users/Arkadiusz/Documents/Vivado Projects/TDC_VernierOsc/TDC_VernierOsc.srcs/sources_1/new/DFF with reset.vhd}
  {C:/Users/Arkadiusz/Documents/Vivado Projects/TDC_VernierOsc/TDC_VernierOsc.srcs/sources_1/new/Licznik_SP.vhd}
  {C:/Users/Arkadiusz/Documents/Vivado Projects/TDC_VernierOsc/TDC_VernierOsc.srcs/sources_1/new/Oscylator_SP.vhd}
  {C:/Users/Arkadiusz/Documents/Vivado Projects/TDC_VernierOsc/TDC_VernierOsc.srcs/sources_1/new/Oscylatory.vhd}
  {C:/Users/Arkadiusz/Documents/Vivado Projects/TDC_VernierOsc/TDC_VernierOsc.srcs/sources_1/new/Liczniki.vhd}
  {C:/Users/Arkadiusz/Documents/Vivado Projects/TDC_VernierOsc/TDC_VernierOsc.srcs/sources_1/new/Detektor_koincyd.vhd}
  {C:/Users/Arkadiusz/Documents/Vivado Projects/TDC_VernierOsc/TDC_VernierOsc.srcs/sources_1/new/Uklad_WE.vhd}
  {C:/Users/Arkadiusz/Documents/Vivado Projects/TDC_VernierOsc/TDC_VernierOsc.srcs/sources_1/new/top.vhd}
}
read_xdc {{C:/Users/Arkadiusz/Documents/Vivado Projects/TDC_VernierOsc/TDC_VernierOsc.srcs/constrs_1/imports/PORTS/VC707VConstraints.xdc}}
set_property used_in_implementation false [get_files {{C:/Users/Arkadiusz/Documents/Vivado Projects/TDC_VernierOsc/TDC_VernierOsc.srcs/constrs_1/imports/PORTS/VC707VConstraints.xdc}}]

synth_design -top top -part xc7vx485tffg1761-2
write_checkpoint -noxdef top.dcp
catch { report_utilization -file top_utilization_synth.rpt -pb top_utilization_synth.pb }
